services:
  localstack:
    container_name: "${LOCALSTACK_CONTAINER_NAME-localstackmaindemo}"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:${LOCALSTACK_PORT:-4566}:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"                      # external services port range
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=lambda,s3,apigateway,logs
      - LAMBDA_DOCKER_NETWORK=${LOCALSTACK_NETWORK_NAME-localstack_network_demo}
      - DEBUG=1
      - PROVIDER_OVERRIDE_STEPFUNCTIONS=v2
    volumes:
      - "./volumes/${LOCALSTACK_VOLUME_DIR:-localstack_persistence}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack_network

  terraform:
    container_name: "${TERRAFORM_CONTAINER_NAME-terraform_for_localstack_demo}"
    image: hashicorp/terraform:1.5.7
    working_dir: /app
    entrypoint: sh -c "sleep inf"
    volumes:
      - "./volumes/${TERRAFORM_VOLUME_DIR:-terraform}:/app"
    networks:
      - localstack_network

networks:
  localstack_network:
    name: "${LOCALSTACK_NETWORK_NAME-localstack_network_demo}"